#!/usr/bin/env bash
# QUICK REFERENCE - Commands to Get Login Working

echo "╔════════════════════════════════════════════════════╗"
echo "║  METAPHARSIC ERP - LOGIN FIX QUICK REFERENCE      ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "COPY & PASTE these commands in order:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Start Backend (Terminal 1)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd server"
echo "npm install"
echo "npm start"
echo ""
echo "⏳ Wait for: '🚀 Server running on port 5000'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Create Admin User (Terminal 2)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd server"
echo "node setup-admin.js"
echo ""
echo "✅ Look for: 'Admin user created successfully!'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Configure Frontend (Terminal 2)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd .."
echo "cp .env.frontend.example .env.local"
echo ""
echo "✓ Edit .env.local if needed (usually not required)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Start Frontend (Terminal 3)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npm install"
echo "npm run dev"
echo ""
echo "⏳ Wait for: '➜ Local: http://localhost:5173/'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Test Login (Browser)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open: http://localhost:5173"
echo "2. Username: admin"
echo "3. Password: admin"
echo "4. Click: Sign In"
echo ""
echo "✅ Should see dashboard"
echo ""

echo "════════════════════════════════════════════════════"
echo "TROUBLESHOOTING"
echo "════════════════════════════════════════════════════"
echo ""
echo "Backend not responding?"
echo "  → ps aux | grep 'node' | grep -v grep"
echo "  → If not running: cd server && npm start"
echo ""
echo "Admin user not created?"
echo "  → cd server && node setup-admin.js"
echo ""
echo "Wrong API URL?"
echo "  → cat .env.local | grep VITE_API_URL"
echo "  → Should be: http://localhost:5000/api"
echo ""
echo "Full diagnostic?"
echo "  → bash diagnose.sh"
echo ""
echo "════════════════════════════════════════════════════"
echo ""
